services:
  mongo:
    image: mongo:7.0
    ports:
      - "27018:27017"
    volumes:
      - ./.mongo-data:/data/db
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Admin123?"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - ./.mssql-data:/var/opt/mssql
    networks:
      - app-network
  apache:
    image: httpd:2.4
    container_name: image-server
    ports:
      - "8081:80"
    volumes:
      - ./images:/usr/local/apache2/htdocs/images
    networks:
      - app-network

volumes:
  mongo-data:
  mssql-data:
  image:

networks:
  app-network:
    driver: bridge
