version: '3.9'

services:
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Admin123?"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql-data:/var/opt/mssql
    networks:
      - app-network

volumes:
  mongo-data:
  mssql-data:

networks:
  app-network:
    driver: bridge
